# $schema: ../schema.json
name: $bitXor
category:
    - 'Bitwise Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bitXor/'
type:
    - resolvesToInt
    - resolvesToLong
encode: single
description: |
    Returns the result of a bitwise xor (exclusive or) operation on an array of int and long values.
    New in version 6.3.
arguments:
    -
        name: expression
        type:
            - resolvesToInt
            - resolvesToLong
        variadic: array
