# $schema: ../schema.json
name: $firstN
category:
    - 'Array Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/firstN-array-element/'
type:
    - accumulator
    - window
encode: object
description: |
    Returns a specified number of elements from the beginning of an array. Distinct from the $firstN accumulator.
arguments:
    -
        name: input
        type:
            - resolvesToArray
        description: |
            An expression that resolves to the array from which to return n elements.
    -
        name: 'n'
        type:
            - resolvesToInt
        description: |
            An expression that resolves to a positive integer. The integer specifies the number of array elements that $firstN returns.
