# $schema: ../schema.json
name: $gt
category:
    - 'Comparison Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/gt/'
type:
    - resolvesToBool
encode: array
description: |
    Returns true if the first value is greater than the second.
arguments:
    -
        name: expression1
        type:
            - expression
    -
        name: expression2
        type:
            - expression
