# $schema: ../schema.json
name: $min
category:
    - Accumulators
    - 'Accumulators (in Other Stages)'
    - 'Window Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/min/'
type:
    - resolvesToAny
    - accumulator
    - window
encode: single
description: |
    Returns the minimum value that results from applying an expression to each document.
    Changed in version 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
        variadic: array
