# $schema: ../schema.json
name: $not

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/not/'
type:
    - resolvesToBool
encode: single
description: |
    Returns the boolean value that is the opposite of its argument expression. Accepts a single argument expression.
arguments:
    -
        name: expression
        type:
            - expression
            - resolvesToBool
