# $schema: ../schema.json
name: $objectToArray

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/objectToArray/'
type:
    - resolvesToArray
encode: single
description: |
    Converts a document to an array of documents representing key-value pairs.
arguments:
    -
        name: object
        type:
            - resolvesToObject
        description: |
            Any valid expression as long as it resolves to a document object. $objectToArray applies to the top-level fields of its argument. If the argument is a document that itself contains embedded document fields, the $objectToArray does not recursively apply to the embedded document fields.
