# $schema: ../schema.json
name: $pow
category:
    - 'Arithmetic Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/pow/'
type:
    - resolvesToNumber
encode: array
description: |
    Raises a number to the specified exponent.
arguments:
    -
        name: number
        type:
            - resolvesToNumber
    -
        name: exponent
        type:
            - resolvesToNumber
