# $schema: ../schema.json
name: $rand

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/rand/'
type:
    - resolvesToDouble
encode: object
description: |
    Returns a random float between 0 and 1
