# $schema: ../schema.json
name: $size
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/size/'
type:
    - resolvesToInt
encode: single
description: |
    Returns the number of elements in the array. Accepts a single expression as argument.
arguments:
    -
        name: expression
        type:
            - resolvesToArray
        description: |
            The argument for $size can be any expression as long as it resolves to an array.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/size/#example'
        pipeline:
            -
                $project:
                    item: 1
                    numberOfColors:
                        $cond:
                            if:
                                # The example in the docs uses the short syntax for $isArray,
                                # but the aggregation builder always uses the more verbose syntax.
                                # $isArray: '$colors'
                                $isArray:
                                    - '$colors'
                            then:
                                $size: '$colors'
                            else: 'NA'
