# $schema: ../schema.json
name: $subtract

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/'
type:
    - resolvesToNumber
    - resolvesToDate
encode: array
description: |
    Returns the result of subtracting the second value from the first. If the two values are numbers, return the difference. If the two values are dates, return the difference in milliseconds. If the two values are a date and a number in milliseconds, return the resulting date. Accepts two argument expressions. If the two values are a date and a number, specify the date argument first as it is not meaningful to subtract a date from a number.
arguments:
    -
        name: expression1
        type:
            - resolvesToNumber
            - resolvesToDate
    -
        name: expression2
        type:
            - resolvesToNumber
            - resolvesToDate
