# $schema: ../schema.json
name: $toLong

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/toLong/'
type:
    - resolvesToLong
encode: single
description: |
    Converts value to a long.
    New in version 4.0.
arguments:
    -
        name: expression
        type:
            - expression
