# $schema: ../schema.json
name: $addToSet
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/addToSet/'
type:
    - accumulator
    - window
encode: single
description: |
    Returns an array of unique expression values for each group. Order of the array elements is undefined.
    Changed in MongoDB 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
