# $schema: ../schema.json
name: $push

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/push/'
type:
    - accumulator
    - window
encode: single
description: |
    Returns an array of values that result from applying an expression to each document.
    Changed in version 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
