# $schema: ../schema.json
name: $elemMatch
category:
    - 'Projection Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/elemMatch/'
type:
    - projection
encode: object
description: |
    Projects the first element in an array that matches the specified $elemMatch condition.
arguments:
    -
        name: query
        type:
            - query
