# $schema: ../schema.json
name: $densify
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/densify/'
type:
    - Stage
encode: object
description: |
    Creates new documents in a sequence of documents where certain values in a field are missing.
arguments:
    -
        name: field
        type:
            - FieldPath
        description: |
            The field to densify. The values of the specified field must either be all numeric values or all dates.
            Documents that do not contain the specified field continue through the pipeline unmodified.
            To specify a <field> in an embedded document or in an array, use dot notation.
    -
        name: partitionByFields
        type:
            - array<string>
        optional: true
        description: |
            The field(s) that will be used as the partition keys.
    -
        name: range
        type:
            - Range
        description: |
            Specification for range based densification.
