# $schema: ../schema.json
name: $group
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/group/'
type:
    - stage
encode: group
description: |
    Groups input documents by a specified identifier expression and applies the accumulator expression(s), if specified, to each group. Consumes all input documents and outputs one document per each distinct group. The output documents only contain the identifier field and, if specified, accumulated fields.
arguments:
    -
        name: _id
        type:
            - expression
        description: |
            The _id expression specifies the group key. If you specify an _id value of null, or any other constant value, the $group stage returns a single document that aggregates values across all of the input documents.
    -
        name: field
        type:
            - accumulator
        variadic: object
        description: |
            Computed using the accumulator operators.
