# $schema: ../schema.json
name: $match
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/match/'
type:
    - Stage
encode: single
description: |
    Filters the document stream to allow only matching documents to pass unmodified into the next pipeline stage. $match uses standard MongoDB queries. For each input document, outputs either one document (a match) or zero documents (no match).
arguments:
    -
        name: query
        type:
            - Query
