buildvariants:
  - name: test-debian11-php-%phpVersion%-local
    tags: ["test", "debian", "x64"]
    display_name: "Test: Debian 11, PHP %phpVersion%"
    run_on: debian11-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian11"
      FETCH_BUILD_TASK: "build-php-%phpVersion%"
      PHP_VERSION: "%phpVersion%"
      VARIANT: debian11 # Referenced by ADL build script for downloading MQLRun
    depends_on:
      - variant: "build-debian11"
        name: "build-php-%phpVersion%"
    tasks:
      - ".standalone .local !.csfle !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - ".replicaset .local !.csfle !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - ".sharded .local !.csfle !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - ".loadbalanced .local !.csfle !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - "test_serverless_task_group"
      - "test_serverless_proxy_task_group"
      - "test-atlas-data-lake"

  - name: test-debian92-php-%phpVersion%-local
    tags: ["test", "debian", "x64"]
    display_name: "Test: Debian 9.2, PHP %phpVersion%"
    run_on: debian92-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian92"
      FETCH_BUILD_TASK: "build-php-%phpVersion%"
      PHP_VERSION: "%phpVersion%"
    depends_on:
      - variant: "build-debian92"
        name: "build-php-%phpVersion%"
    tasks:
      # Remember to add new major versions here as they are released
      - ".standalone .local !.csfle !.6.0 !.7.0 !.rapid !.latest"
      - ".replicaset .local !.csfle !.6.0 !.7.0 !.rapid !.latest"
      - ".sharded .local !.csfle !.6.0 !.7.0 !.rapid !.latest"
      - ".loadbalanced .local !.csfle !.6.0 !.7.0 !.rapid !.latest"

  # Test with upcoming PHPC versions
  - name: test-debian11-php-%phpVersion%-phpc-next-stable
    tags: ["test", "debian", "x64"]
    display_name: "Test: Debian 11, PHP %phpVersion%, PHPC next-stable"
    run_on: debian11-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian11"
      FETCH_BUILD_TASK: "build-php-%phpVersion%-next-stable"
      PHP_VERSION: "%phpVersion%"
    depends_on:
      - variant: "build-debian11"
        name: "build-php-%phpVersion%-next-stable"
    tasks:
      - ".replicaset .local .7.0 !.csfle"

  - name: test-debian11-php-%phpVersion%-phpc-next-minor
    tags: ["test", "debian", "x64"]
    display_name: "Test: Debian 11, PHP %phpVersion%, PHPC next-minor"
    run_on: debian11-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian11"
      FETCH_BUILD_TASK: "build-php-%phpVersion%-next-minor"
      PHP_VERSION: "%phpVersion%"
    depends_on:
      - variant: "build-debian11"
        name: "build-php-%phpVersion%-next-minor"
    tasks:
      - ".replicaset .local .7.0 !.csfle"

  # Test Atlas and CSFLE on RHEL 8
  - name: test-rhel80-php-%phpVersion%-atlas
    tags: ["test", "debian", "x64"]
    display_name: "Test: RHEL 8.0, PHP %phpVersion%"
    run_on: rhel80-small
    expansions:
      FETCH_BUILD_VARIANT: "build-rhel80"
      FETCH_BUILD_TASK: "build-php-%phpVersion%"
      PHP_VERSION: "%phpVersion%"
    depends_on:
      - variant: "build-rhel80"
        name: "build-php-%phpVersion%"
    tasks:
      - "test_atlas_task_group"
      - ".csfle"

