# $schema: ../schema.json
name: $listSampledQueries
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/listSampledQueries/'
type:
    - stage
encode: object
description: |
    Lists sampled queries for all collections or a specific collection.
arguments:
    -
        name: namespace
        type:
            - string
        optional: true
