# $schema: ../schema.json
name: $merge

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/merge/'
type:
    - stage
encode: object
description: |
    Writes the resulting documents of the aggregation pipeline to a collection. The stage can incorporate (insert new documents, merge documents, replace documents, keep existing documents, fail the operation, process documents with a custom update pipeline) the results into an output collection. To use the $merge stage, it must be the last stage in the pipeline.
    New in version 4.2.
arguments:
    -
        name: into
        type:
            - string
            #- OutCollection
        description: |
            The output collection.
    -
        name: 'on'
        type:
            - string
            - array # of string
        optional: true
        description: |
            Field or fields that act as a unique identifier for a document. The identifier determines if a results document matches an existing document in the output collection.
    -
        name: let
        type:
            - object
        optional: true
        description: |
            Specifies variables for use in the whenMatched pipeline.
    -
        name: whenMatched
        type:
            - string # WhenMatched
        optional: true
        description: |
            The behavior of $merge if a result document and an existing document in the collection have the same value for the specified on field(s).
    -
        name: whenNotMatched
        type:
            - WhenNotMatched
        optional: true
        description: |
            The behavior of $merge if a result document does not match an existing document in the out collection.
