# $schema: ../schema.json
name: $planCacheStats

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/planCacheStats/'
type:
    - stage
encode: object
description: |
    Returns plan cache information for a collection.
