# $schema: ../schema.json
name: $set

link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/set/'
type:
    - stage
encode: single
description: |
    Adds new fields to documents. Outputs documents that contain all existing fields from the input documents and newly added fields.
    Alias for $addFields.
arguments:
    -
        name: field
        type:
            - expression
        variadic: object
