# $schema: ../schema.json
name: $setWindowFields
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/'
type:
    - stage
encode: object
description: |
    Groups documents into windows and applies one or more operators to the documents in each window.
    New in version 5.0.
arguments:
    -
        name: partitionBy
        type:
            - expression
        description: |
            Specifies an expression to group the documents. In the $setWindowFields stage, the group of documents is known as a partition. Default is one partition for the entire collection.
    -
        name: sortBy
        type:
            - SortSpec
        description: |
            Specifies the field(s) to sort the documents by in the partition. Uses the same syntax as the $sort stage. Default is no sorting.
    -
        name: output
        type:
            - object
        description: |
            Specifies the field(s) to append to the documents in the output returned by the $setWindowFields stage. Each field is set to the result returned by the window operator.
            A field can contain dots to specify embedded document fields and array fields. The semantics for the embedded document dotted notation in the $setWindowFields stage are the same as the $addFields and $set stages.
    -
        name: window
        type:
            - Window
        optional: true
        description: |
            Specifies the window boundaries and parameters. Window boundaries are inclusive. Default is an unbounded window, which includes all documents in the partition.
