# $schema: ../schema.json
name: $shardedDataDistribution
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/shardedDataDistribution/'
type:
    - stage
encode: object
description: |
    Provides data and size distribution information on sharded collections.
    New in MongoDB 6.0.3.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/shardedDataDistribution/#examples'
        pipeline:
            -
                $shardedDataDistribution: {}
