# $schema: ../schema.json
name: $unwind
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/'
type:
    - stage
encode: object
description: |
    Deconstructs an array field from the input documents to output a document for each element. Each output document replaces the array with an element value. For each input document, outputs n documents where n is the number of array elements and can be zero for an empty array.
arguments:
    -
        name: path
        type:
            - arrayFieldPath
        description: |
            Field path to an array field.
    -
        name: includeArrayIndex
        type:
            - string
        optional: true
        description: |
            The name of a new field to hold the array index of the element. The name cannot start with a dollar sign $.
    -
        name: preserveNullAndEmptyArrays
        type:
            - bool
        optional: true
        description: |
            If true, if the path is null, missing, or an empty array, $unwind outputs the document.
            If false, if path is null, missing, or an empty array, $unwind does not output a document.
            The default value is false.
