# $schema: ../schema.json
name: $and
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/and/'
type:
    - query
encode: single
description: |
    Joins query clauses with a logical AND returns all documents that match the conditions of both clauses.
arguments:
    -
        name: queries
        type:
            - query
        variadic: array
        variadicMin: 1
