# $schema: ../schema.json
name: $exists

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/exists/'
type:
    - filter
encode: single
description: |
    Matches documents that have the specified field.
arguments:
    -
        name: exists
        type:
            - bool
