# $schema: ../schema.json
name: $geoIntersects

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/geoIntersects/'
type:
    - filter
encode: single
description: |
    Selects geometries that intersect with a GeoJSON geometry. The 2dsphere index supports $geoIntersects.
arguments:
    -
        name: geometry
        type:
            - geometry
