# $schema: ../schema.json
name: $geometry
category:
    - 'Geospatial Geometry Specifiers'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/geometry/'
type:
    - geometry
encode: object
description: |
    Specifies a geometry in GeoJSON format to geospatial query operators.
arguments:
    -
        name: type
        type:
            - string
    -
        name: coordinates
        type:
            - array
    -
        name: crs
        type:
            - object
