# $schema: ../schema.json
name: $geoWithin

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/geoWithin/'
type:
    - fieldQuery
encode: single
description: |
    Selects geometries within a bounding GeoJSON geometry. The 2dsphere and 2d indexes support $geoWithin.
arguments:
    -
        name: geometry
        type:
            - geometry
