# $schema: ../schema.json
name: $lt

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/lt/'
type:
    - fieldQuery
encode: single
description: |
    Matches values that are less than a specified value.
arguments:
    -
        name: value
        type:
            - any
