# $schema: ../schema.json
name: $lte

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/lte/'
type:
    - fieldQuery
encode: single
description: |
    Matches values that are less than or equal to a specified value.
arguments:
    -
        name: value
        type:
            - any
