# $schema: ../schema.json
name: $nin

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/nin/'
type:
    - fieldQuery
encode: single
description: |
    Matches none of the values specified in an array.
arguments:
    -
        name: value
        type:
            - array # of expression
