# $schema: ../schema.json
name: $size

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/size/'
type:
    - fieldQuery
encode: single
description: |
    Selects documents if the array field is a specified size.
arguments:
    -
        name: value
        type:
            - int
