# $schema: ../schema.json
name: $type

link: 'https://www.mongodb.com/docs/manual/reference/operator/query/type/'
type:
    - fieldQuery
encode: single
description: |
    Selects documents if a field is of the specified type.
arguments:
    -
        name: type
        type:
            - int
            - string
            - array # of int or string
