# $schema: ../schema.json
name: $and
category:
    - 'Boolean Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/and/'
type:
    - resolvesToBool
encode: single
description: |
    Returns true only when all its expressions evaluate to true. Accepts any number of argument expressions.
arguments:
    -
        name: expression
        type:
            - expression
            - resolvesToBool
            - resolvesToNumber
            - resolvesToString
            - resolvesToNull
        variadic: array
