# $schema: ../schema.json
name: $bitAnd
category:
    - 'Bitwise Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/bitAnd/'
type:
    - resolvesToInt
    - resolvesToLong
encode: single
description: |
    Returns the result of a bitwise and operation on an array of int or long values.
    New in version 6.3.
arguments:
    -
        name: expression
        type:
            - resolvesToInt
            - resolvesToLong
        variadic: array
