# $schema: ../schema.json
name: $covarianceSamp
category:
    - 'Window Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/covarianceSamp/'
type:
    - resolvesToDouble
    - resolvesToDecimal
encode: array
description: |
    Returns the sample covariance of two numeric expressions.
    New in version 5.0.
arguments:
    -
        name: expression1
        type:
            - resolvesToNumber
    -
        name: expression2
        type:
            - resolvesToNumber
