# $schema: ../schema.json
name: $divide
category:
    - 'Arithmetic Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/divide/'
type:
    - resolvesToDouble
encode: array
description: |
    Returns the result of dividing the first number by the second. Accepts two argument expressions.
arguments:
    -
        name: dividend
        type:
            - resolvesToNumber
        description: |
            The first argument is the dividend, and the second argument is the divisor; i.e. the first argument is divided by the second argument.
    -
        name: divisor
        type:
            - resolvesToNumber
