# $schema: ../schema.json
name: $isoDayOfWeek
category:
    - 'Date Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/isoDayOfWeek/'
type:
    - resolvesToInt
encode: object
description: |
    Returns the weekday number in ISO 8601 format, ranging from 1 (for Monday) to 7 (for Sunday).
arguments:
    -
        name: date
        type:
            - resolvesToDate
            - resolvesToTimestamp
            - resolvesToObjectId
        description: |
            The date to which the operator is applied. date must be a valid expression that resolves to a Date, a Timestamp, or an ObjectID.
    -
        name: timezone
        type:
            - resolvesToString
        optional: true
        description: |
            The timezone of the operation result. timezone must be a valid expression that resolves to a string formatted as either an Olson Timezone Identifier or a UTC Offset. If no timezone is provided, the result is displayed in UTC.
