# $schema: ../schema.json
name: $round
category:
    - 'Arithmetic Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/round/'
type:
    - resolvesToInt
    - resolvesToDouble
    - resolvesToDecimal
    - resolvesToLong
encode: array
description: |
    Rounds a number to to a whole integer or to a specified decimal place.
arguments:
    -
        name: number
        type:
            - resolvesToInt
            - resolvesToDouble
            - resolvesToDecimal
            - resolvesToLong
        description: |
            Can be any valid expression that resolves to a number. Specifically, the expression must resolve to an integer, double, decimal, or long.
            $round returns an error if the expression resolves to a non-numeric data type.
    -
        name: place
        type:
            - resolvesToInt
        optional: true
        description: |
            Can be any valid expression that resolves to an integer between -20 and 100, exclusive.
