# $schema: ../schema.json
name: $setEquals
category:
    - 'Set Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/setEquals/'
type:
    - resolvesToBool
encode: single
description: |
    Returns true if the input sets have the same distinct elements. Accepts two or more argument expressions.
arguments:
    -
        name: expression
        type:
            - resolvesToArray
        variadic: array
