name: "Generator"

on:
  merge_group:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

env:
  PHP_VERSION: "8.2"
  # TODO: change to "stable" once 2.0.0 is released
  # DRIVER_VERSION: "stable"
  DRIVER_VERSION: "mongodb/mongo-php-driver@v2.x"

jobs:
  psalm:
    name: "Diff check"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup"
        uses: "./.github/actions/setup"
        with:
          php-version: ${{ env.PHP_VERSION }}
          driver-version: ${{ env.DRIVER_VERSION }}
          working-directory: "generator"

      - name: "Run Generator"
        run: "generator/generate"

      - name: "Check file diff"
        run: git add . -N && git diff --exit-code
